site_name: Warmo's Stuff
theme:
    name: material
    language: en
    palette:
        scheme: slate
        primary: green
        accent: orange
    features:
        navigation.instant
        navigation.instant.progress
        navigation.tracking
        navigation.sections
        navigation.tabs
        navigation.tabs.sticky
        toc.integrate
    logo: images/icons/maze-cornea.png
    favicon: images/icons/maze-cornea.png
plugins:
    - awesome-pages
    - blog:
        categories: true
        blog_dir: projects
        archive: false
    - search
    - git-revision-date-localized:
        exclude:
            - Projects/*
    - open-in-new-tab
    - git-latest-changes:
        history_limit: 5
#        repo_vendor: github
# If unset, it will use the gh_pages branch and spam the list
        limit_to_docs_dir: true
        enabled_on_serve: true
markdown_extensions:
#    - pymdownx.keys
#    - pymdownx.smartsymbols
    - attr_list
    - md_in_html
    - tables
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: |
  &copy; 2024 <a href="https://github.com/MrWarmo"  target="_blank" rel="noopener">Jake W</a>
repo_url: https://github.com/MrWarmo/mrwarmo.github.io
#extra_css:
#    - stylesheets/extra.css