site_name: Warmo's Stuff
site_url: http://warmolabs.tf
theme:
    name: material
    custom_dir: docs/overrides
    language: en
    palette:
        scheme: slate
        primary: green
        accent: orange
    features:
        navigation.instant
        navigation.tracking
        navigation.sections
        navigation.tabs
        navigation.tabs.sticky
        toc.integrate
        search.highlight
    logo: images/icons/maze-cornea.png
    favicon: images/icons/maze-cornea-t.png
    font:
        text: Pixelify Sans
plugins:
    - awesome-pages
    - blog:
        categories: true
        blog_dir: work
        archive: false
        authors: false
        post_readtime: false
    - search
    - open-in-new-tab
markdown_extensions:
#    - pymdownx.keys
#    - pymdownx.smartsymbols
    - pymdownx.blocks.caption
    - def_list
    - attr_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - md_in_html
    - tables
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: |
  &copy; 2024 <a href="https://github.com/MrWarmo"  target="_blank" rel="noopener">Jake W</a>
repo_url: https://github.com/MrWarmo/mrwarmo.github.io
extra_css:
    - stylesheets/extra.css
#extra:
#  social:
#    - icon: fontawesome/brands/bluesky
#      link: https://bsky.app/profile/warmo.bsky.social