site_name: Warmo's Stuff
theme:
    name: material
    language: en
    palette:
        scheme: slate
        primary: green
        accent: orange
    features:
        navigation.instant
        navigation.instant.progress
        navigation.tracking
        navigation.sections
        navigation.tabs
        navigation.tabs.sticky
        toc.integrate
    logo: maze-white.svg
    favicon: maze-white.svg
plugins:
    - awesome-pages
    - blog:
        categories: false
    - search
    - git-revision-date-localized
    - open-in-new-tab
    - git-latest-changes:
        history_limit: 5
        repo_vendor: github
        limit_to_docs_dir: true
markdown_extensions:
#    - pymdownx.keys
#    - pymdownx.smartsymbols
    - attr_list
    - md_in_html
    - tables
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: |
  &copy; 2024 <a href="https://github.com/MrWarmo"  target="_blank" rel="noopener">Jake W</a>
repo_url: https://github.com/MrWarmo/mrwarmo.github.io