name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: pip install pillow cairosvg
#      - run: pip3 install git+https://github.com/tombreit/mkdocs-git-latest-changes-plugin.git@319c36c4ad28cc0f734e377f9397a46d4c13e305
# Need to use this specific version or history_limit setting doesnt work for some reason
#      - run: pip3 install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-open-in-new-tab
      - run: pip install mkdocs-awesome-pages-plugin
#      - run: pip install mkdocs-nav-weight
      - run: mkdocs gh-deploy --force